apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: namegen
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/part-of: namegen-devops-project
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6
          ports:
            - name: mongodb
              containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: namegen
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongodb-init-script
          configMap:
            name: mongodb-init-script
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ebs-gp3
        resources:
          requests:
            storage: 5Gi
