apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: namegen
data:
  init-user.js: |
    db = db.getSiblingDB("namegen");
    db.createUser({
      user: "genuser",
      pwd: "password",
      roles: [
        {
          role: "readWrite",
          db: "namegen"
        }
      ]
    });
    
