apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: namegen
type: Opaque
stringData:
  username: genuser
  password: password
  mongodb-url: mongodb://genuser:password@mongodb/namegen
